name: bench
channels:
- anaconda
- pytorch
dependencies:
- python=3.8
- pytorch=1.10.1
- cudatoolkit=11.3
- torchvision
- pip
- pip:
  - llcv==0.0.6
  - https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/mmcv_full-1.4.6-cp38-cp38-manylinux1_x86_64.whl
  - mmdet==2.21.0
